FROM centos

RUN yum -y install epel-release
RUN yum -y install python-pip git
RUN pip install pytest
RUN curl -L -O https://github.com/openshift/origin/releases/download/v1.5.1/openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit.tar.gz &&\
    tar xzf openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit.tar.gz &&\
    cp openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit/oc /usr/bin/oc


WORKDIR /opt/saasherder

ADD requirements.txt /opt/saasherder
RUN pip install -r requirements.txt

ADD . /opt/saasherder 
ENV PYTHONPATH=/opt/saasherder/saasherder/

CMD pytest