FROM centos

RUN yum -y install epel-release centos-release-openshift-origin
RUN yum -y install python-pip git origin-clients
RUN pip install pytest

WORKDIR /opt/saasherder

ADD requirements.txt /opt/saasherder
RUN pip install -r requirements.txt

ADD . /opt/saasherder 
ENV PYTHONPATH=/opt/saasherder/saasherder/

CMD pytest